FROM golang:1.19-alpine

ARG ZSH_IN_DOCKER_VERSION=1.1.2


# Install useful tools
RUN apk --no-cache upgrade && \
  apk --no-cache add ca-certificates curl gnupg jq bash tar openssl util-linux nano zsh-syntax-highlighting less procps lsof postgresql-client alpine-sdk

# Install zsh-in-docker
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v${ZSH_IN_DOCKER_VERSION}/zsh-in-docker.sh)" -- \
  -t clean \
  -p git \
  -p node \
  -p yarn \
  -p history \
  -p https://github.com/zsh-users/zsh-autosuggestions \
  -p https://github.com/zsh-users/zsh-completions
RUN echo "source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> /root/.zshrc

# Working directory inside container
WORKDIR /app

EXPOSE  3000

RUN go install github.com/go-delve/delve/cmd/dlv@latest && go install github.com/Khan/genqlient@latest

CMD [ "/bin/zsh", "-c" ]